-- MySQL Script generated by MySQL Workbench
-- Tue Jul 11 18:29:18 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema freshmeat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema freshmeat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `freshmeat` DEFAULT CHARACTER SET utf8 ;
USE `freshmeat` ;

-- -----------------------------------------------------
-- Table `freshmeat`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `freshmeat`.`Category` (
  `category_id` INT NOT NULL,
  `category_name` VARCHAR(50) NULL,
  PRIMARY KEY (`category_id`),
  UNIQUE INDEX `category_name_UNIQUE` (`category_name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `freshmeat`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `freshmeat`.`Product` (
  `product_id` INT NOT NULL,
  `product_name` VARCHAR(200) NULL,
  `product_price` DECIMAL(8,2) NULL DEFAULT 0.00,
  `product_brand` VARCHAR(20) NULL,
  `product_location` VARCHAR(20) NULL,
  `shipping_location` VARCHAR(20) NULL,
  `preview_image` INT NULL,
  `detail_image` INT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`product_id`),
  INDEX `fk_Product_Category1_idx` (`category_id` ASC),
  CONSTRAINT `fk_Product_Category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `freshmeat`.`Category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `freshmeat`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `freshmeat`.`User` (
  `username` VARCHAR(16) NULL,
  `email` VARCHAR(256) NULL,
  `password` VARCHAR(256) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`user_id`));


-- -----------------------------------------------------
-- Table `freshmeat`.`Review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `freshmeat`.`Review` (
  `review_id` INT NOT NULL,
  `review_comment` VARCHAR(200) NULL,
  `user_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`review_id`),
  INDEX `fk_Review_User1_idx` (`user_id` ASC),
  INDEX `fk_Review_Product1_idx` (`product_id` ASC),
  CONSTRAINT `fk_Review_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `freshmeat`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Review_Product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `freshmeat`.`Product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `freshmeat`.`OrderList`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `freshmeat`.`OrderList` (
  `order_id` INT NOT NULL DEFAULT -1,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `user_id` INT NOT NULL,
  `ship_address` VARCHAR(200) NULL,
  `ship_name` VARCHAR(20) NULL,
  `mobile` CHAR(11) NULL,
  `payment_state` CHAR NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_Order_User1_idx` (`user_id` ASC),
  CONSTRAINT `fk_Order_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `freshmeat`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `freshmeat`.`OrderItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `freshmeat`.`OrderItem` (
  `amount` INT NULL,
  `order_item_id` INT NOT NULL,
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`order_item_id`),
  INDEX `fk_OrderItem_Order1_idx` (`order_id` ASC),
  INDEX `fk_OrderItem_Product1_idx` (`product_id` ASC),
  INDEX `fk_OrderItem_User1_idx` (`user_id` ASC),
  CONSTRAINT `fk_OrderItem_Order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `freshmeat`.`OrderList` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrderItem_Product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `freshmeat`.`Product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrderItem_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `freshmeat`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
